name: Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node bez cache (nevyžaduje lockfile)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install

      - name: Build web
        run: npm run build

      # Pridaj Android platformu, ak ešte nie je pridaná
      - name: Add Android platform
        run: |
          if [ -d "android" ]; then
            echo "Android already added, skipping."
          else
            npx cap add android
          fi

      - name: Sync Capacitor (Android)
        run: npx cap sync android

      # Istota: povolenie KAMERY v manifeste
      - name: Ensure CAMERA permission
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST" ]; then
            if ! grep -q 'android.permission.CAMERA' "$MANIFEST"; then
              # doplň xmlns:tools, ak chýba
              if ! grep -q 'xmlns:tools=' "$MANIFEST"; then
                sed -i 's#<manifest #<manifest xmlns:tools="http://schemas.android.com/tools" #' "$MANIFEST"
              fi
              sed -i 's#<application#<uses-permission android:name="android.permission.CAMERA"/>\n    <application#' "$MANIFEST"
            fi
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
